<?php

namespace AppBundle\Repository\Gerente;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * GerenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GerenteRepository extends DocumentRepository
{
    /**
     * @return array
     */
    public function getAllGerentes(){
        $gerentes = array();
        $gerentesGross = $this->createQueryBuilder()
            ->sort('apellidos', 'ASC')
            ->getQuery()
            ->execute();
        foreach($gerentesGross as $gerente)
        {
            $gerentes[] = array(
                'id'            => $gerente->getId(),
                'nombre'        => $gerente->getNombre(),
                'apellidos'     => $gerente->getApellidos(),
                'email'         => $gerente->getEmail(),
            );
        }

        return $gerentes;
    }
}