<?php

namespace AppBundle\Repository\Medico;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoRepository extends DocumentRepository
{
}