<?php

namespace AppBundle\Repository\Pago;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoRepository extends DocumentRepository
{
}