<?php

namespace AppBundle\Repository\Producto;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends DocumentRepository
{
	/**
     * @return array
     */
    public function getAll()
    {
        $productos = array();
        $productosGross = $this->createQueryBuilder()
            ->getQuery()
            ->execute();

        foreach($productosGross as $producto) {
            $productos[] = array(
                'id'                => $producto->getId(),
                'nombre'            => $producto->getNombre(),
                'precio'        	=> $producto->getPrecio(),
                'laboratorio'       => $producto->getLaboratorio(),
                'existencias'    	=> $producto->getExistencias(),
                'cantidad'         	=> $producto->getCantidad()
            );
        }

        return $productos;
    }
}