<?php

namespace AppBundle\Repository\Producto;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends DocumentRepository
{
}