#Agregar rutas para el api rest

#medico:
#    type:     rest
#    resource: AppBundle\Controller\Api\Medico\MedicoController
#    name_prefix: api_
producto:
    type:     rest
    resource: AppBundle\Controller\Api\Producto\ProductoController
    name_prefix: api_
gerente:
    type:     rest
    resource: AppBundle\Controller\Api\Gerente\GerenteController
    name_prefix: api_
medico:
    type:     rest
    resource: AppBundle\Controller\Api\Medico\MedicoController
    name_prefix: api_
enfermera:
    type:     rest
    resource: AppBundle\Controller\Api\Enfermera\EnfermeraController
    name_prefix: api_
cajero:
    type:     rest
    resource: AppBundle\Controller\Api\Cajero\CajeroController
    name_prefix: api_
paciente:
    type:     rest
    resource: AppBundle\Controller\Api\Paciente\PacienteController
    name_prefix: api_
expediente:
    type:     rest
    resource: AppBundle\Controller\Api\Expediente\ExpedienteController
    name_prefix: api_