<?php

namespace AppBundle\Repository\Enfermera;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * EnfermeraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfermeraRepository extends DocumentRepository
{
    
}