<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GerenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GerenteRepository extends EntityRepository
{
}
