# Rutas de la aplicación
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
# REST Routes
app_rest:
    type: rest
    resource: "@AppBundle/Resources/config/api/routing.yml"
    prefix: /api
#FOS Routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
#FOS USER BUNDLE
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login:
    path:     /clinica/login
    defaults: { _controller: AppBundle:Login/Login:login}
