# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN : [ ROLE_GERENTE, ROLE_MEDICO ]
        ROLE_ADMIN       : [ ROLE_MEDICO, ROLE_ENFERMERA , ROLE_CAJERO , ROLE_PACIENTE]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/clinica/login$
            security: false
        registrar_paciente:
            pattern:  ^/registrar-paciente/$
            security: false
        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                #success_handler: authentication_handler
                always_use_default_target_path: true
                login_path: /clinica/login
                default_target_path: /
            logout:    true
            anonymous: false
            security: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/api/[^/]+, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/clinica/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registrar-paciente/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/clinica/, role: ROLE_SUPER_ADMIN }
        - { path: ^/, role: [ ROLE_GERENTE, ROLE_ENFERMERA, ROLE_MEDICO, ROLE_CAJERO, ROLE_PACIENTE ] }