<?php

namespace AppBundle\Repository\Consulta;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ConsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaRepository extends DocumentRepository
{
}