home:
    path:     /
    defaults: { _controller: AppBundle:Index/Index:index }
#Medico
#medico:
#    path:     /medico
#    defaults: { _controller: AppBundle:Medico/Medico:index}
#Cajero
productos:
    path:     /productos
    defaults: { _controller: AppBundle:Producto/Producto:index}

#Paciente
agendar_cita_paciente:
    path:     /agendar-cita/paciente
    defaults: { _controller: AppBundle:Paciente/Cita:agendar}

registrar_paciente:
  path: /registrar-paciente/
  defaults: {_controller: AppBundle:Paciente/Paciente:registrarPaciente}
