home:
    path:     /
    defaults: { _controller: AppBundle:Index/Index:index }
medico:
    path:     /medico
    defaults: { _controller: AppBundle:Medico/Medico:index}
productos:
    path:     /productos
    defaults: { _controller: AppBundle:Producto/Producto:index}
#Estructura