home:
    path:     /
    defaults: { _controller: AppBundle:Index/Index:index }
#Medico
#medico:
#    path:     /medico
#    defaults: { _controller: AppBundle:Medico/Medico:index}
#Cajero
productos:
    path:     /registrar-producto/
    defaults: { _controller: AppBundle:Producto/Producto:registrarProducto}

buscar_medicamento:
    path:     /buscar-medicamento/
    defaults: { _controller: AppBundle:Producto/Producto:buscarProducto}
#Paciente

consultar_datos:
    path:     /mis-datos/
    defaults: { _controller: AppBundle:Paciente/Paciente:getDatos}

agendar_cita_paciente:
    path:     /agendar-cita/paciente
    defaults: { _controller: AppBundle:Paciente/Cita:agendar}

registrar_paciente:
  path: /registrar-paciente/
  defaults: {_controller: AppBundle:Paciente/Paciente:registrarPaciente}
  
consultar_pacientes:
  path: /consultar-paciente/
  defaults: {_controller: AppBundle:Paciente/Paciente:getPacientes}

registrar_cajero:
  path: /registrar-cajero/
  defaults: {_controller: AppBundle:Cajero/Cajero:registrarCajero}

registrar_medico:
  path: /registrar-medico/
  defaults: {_controller: AppBundle:Medico/Medico:registrarMedico}

registrar_gerente:
  path: /registrar-gerente/
  defaults: {_controller: AppBundle:Gerente/Gerente:registrarGerente}

registrar_enfermera:
  path: /registrar-enfermera/
  defaults: {_controller: AppBundle:Enfermera/Enfermera:registrarEnfermera}

registrar_paciente_enfermera:
  path: /enfermera/registrar-paciente/
  defaults: {_controller:AppBundle:Enfermera/Enfermera:registrarPaciente}

mostrar_paceintes_enfermera:
  path: /enfermera/mostrar-pacientes/
  defaults: {_controller:AppBundle:Enfermera/Enfermera:mostrarPacientes}

enfermera_agendar_cita:
  path: /enfermera/agendar-cita/{id}
  defaults: {_controller:AppBundle:Enfermera/Enfermera:agendarCitaPaciente}


consultar_actividad_diaria:
  path: /gerente/actividad-diaria/
  defaults: {_controller:AppBundle:Gerente/Gerente:getConsultasDia}
consultar_actividad_mensual:
  path: /gerente/actividad-mensual/
  defaults: {_controller:AppBundle:Gerente/Gerente:getConsultasMes}
crear_expediente:
    path:     /expediente/crear/{id}
    defaults: { _controller: AppBundle:Expediente/Expediente:crear }

registrar_medicamento:
    path:     /registrar-medicamento/
    defaults: { _controller: AppBundle:Medicamento/Medicamento:registrarMedicamento}

consultar_medicamentos:
  path: /consultar-medicamentos/
  defaults: { _controller: AppBundle:Medicamento/Medicamento:getMedicamentos}

consultar_inventario:
  path: /consultar-inventario/
  defaults: { _controller: AppBundle:Producto/Producto:getInventario}

consultar_citas_paciente:
  path: /consultar-citas-paciente/
  defaults: { _controller: AppBundle:Paciente/Paciente:getCitas }

registrar_pago_cita:
    path:     /pagar-cita/
    defaults: { _controller: AppBundle:Cajero/Cajero:registrarPagoCita }

consultar_cita_medico:
    path:     /medico/consultar-citas
    defaults: { _controller: AppBundle:Medico/Medico:consultarCitas }

medico_consultar_citas:
  path: /medico/consultar-citas/
  defaults: {_controller: AppBundle:Medico/Medico:consultarCitas}

medico_dar_consulta:
  path: /medico/dar-consulta/{fecha}
  defaults: {_controller: AppBundle:Medico/Medico:darConsulta}

consultar_citas_enfermera:
  path: /enfermera/consultar-citas/
  defaults: {_controller: AppBundle:Enfermera/Enfermera:consultarCitasEnfermera}

gerente_consultar_ventas_diarias:
  path: /gerente/consultar-ventas-hoy/
  defaults: {_controller: AppBundle:Gerente/Gerente:getArticulosVendidosDia}

gerente_consultar_ventas_mes:
  path: /gerente/consultar-ventas-mes/
  defaults: {_controller: AppBundle:Gerente/Gerente:getArticulosVendidosMes}


