#Agregar servicios para formularios aquí
services:
    clinica.form.registration:
        class: AppBundle\Form\Type\User\RegistrationType
        tags:
            - { name: form.type, alias: form_registration }
    clinica.form.medico:
        class: AppBundle\Form\Type\Medico\MedicoType
        tags:
            - { name: form.type, alias: form_medico }
    clinica.form.gerente:
        class: AppBundle\Form\Type\Gerente\GerenteType
        tags:
            - { name: form.type, alias: form_paciente }
    clinica.form.enfermera:
        class: AppBundle\Form\Type\Enfermera\EnfermeraType
        tags:
            - { name: form.type, alias: form_paciente }
    clinica.form.cajero:
        class: AppBundle\Form\Type\Cajero\CajeroType
        tags:
            - { name: form.type, alias: form_producto }
    clinica.form.paciente:
        class: AppBundle\Form\Type\Paciente\PacienteType
        tags:
            - { name: form.type, alias: form_paciente }
    clinica.form.paciente_cita:
        class: AppBundle\Form\Type\Paciente\CitaType
        tags:
            - { name: form.type, alias: form_paciente_cita }

