#Agregar servicios para formularios aquí
services:
    clinica.form.direccion:
        class: AppBundle\Form\Type\DireccionType
        tags:
            - { name: form.type, alias: form_direccion }
    clinica.form.registration:
            class: AppBundle\Form\Type\RegistrationType
            tags:
                - { name: form.type, alias: form_registration }
    clinica.form.medico:
        class: AppBundle\Form\Type\MedicoType
        tags:
            - { name: form.type, alias: form_medico }
    clinica.form.medico_telefono:
        class: AppBundle\Form\Type\TelefonoType
        tags:
            - { name: form.type, alias: form_medico_telefono }
    clinica.form.medico_email:
        class: AppBundle\Form\Type\EmailType
        tags:
            - { name: form.type, alias: form_medico_email }
    clinica.form.producto:
        class: AppBundle\Form\Type\ProductoType
        tags:
            - { name: form.type, alias: form_producto }
    clinica.form.paciente:
        class: AppBundle\Form\Type\PacienteType
        tags:
            - { name: form.type, alias: form_paciente }