<?php

namespace AppBundle\Repository\Cajero;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CajeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajeroRepository extends DocumentRepository
{
}