<?php

namespace AppBundle\Repository\Paciente;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends DocumentRepository
{
}