<?php

namespace AppBundle\Repository\User;

use AppBundle\Document\User\User;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{

    /**
     * @return array
     */
    public function getAllUsers($userType)
    {
        $gerentes = array();
        $gerentesGross = $this->createQueryBuilder()
            ->field($userType)->exists(true)
            ->getQuery()
            ->execute();
        foreach($gerentesGross as $gerente) {
            $gerentes[] = array(
                'id'            => $gerente->getId(),
                'nombre'        => $gerente->getUserName(),
                'email'         => $gerente->getEmail()
            );
        }

        return $gerentes;
    }

    /**
     * @return array
     */
    public function getAllAppointments()
    {
        $appoints = array();
        $appointGross = $this->createQueryBuilder()
            //->select('paciente')
            ->field('paciente')->exists(true)
            //->field('paciente.citas')->exists(true)
            ->getQuery()
            ->execute();

        foreach($appointGross as $appoint) {
            foreach($appoint->getPaciente()->getCitas() as $fecha){
                $appoints[] = $fecha->getFecha() ;
            }
        }
        return $appoints;
    }

    /**
     * @return array
     */
    public function getAppointments($month)
    {
        $appoints = array();
        $appointGross = $this->createQueryBuilder()
            //->select('paciente')
            ->field('paciente')->exists(true)
            //->field('paciente.citas')->exists(true)
            ->getQuery()
            ->execute();

        foreach($appointGross as $appoint) {
            foreach($appoint->getPaciente()->getCitas() as $cita){
                $appoints[] = array(
                    'consultorio'   => $cita->getConsultorio(),
                    'fecha'         => $cita->getFecha()->format('d-m-Y h:i'),
                    'medico'        => $cita->getMedico()
                    );
            }
        }

        return $appoints;
    }
}