<?php

namespace AppBundle\Repository\Medicamento;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MedicamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentoRepository extends DocumentRepository
{
}